using Tyuiu.RadchenkoAV.Sprint5.Task7.V22.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #5 | Выполнил: РадченкоАВ | РППБ -25-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #5                                                               *");
Console.WriteLine("* Тема: Работа в С#                                                       *");
Console.WriteLine("* Задание #7                                                              *");
Console.WriteLine("* Вариант #22                                                             *");
Console.WriteLine("* Выполнил: РадченкоАВ | РППБ -25-1                                       *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* Создать папку в ручную С:\\DataSprint5\\ и скопировать в неё файл)      *");
Console.WriteLine("* Заменить все знаки препинания на #.Полученный результат сохранить в файл*");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                        *");
Console.WriteLine("***************************************************************************");
string path = Path.Combine("C:", "DataSprint5", "InPutDataFileTask7V22.txt");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                              *");
Console.WriteLine("***************************************************************************");
string res = ds.LoadDataAndSave(path);
Console.WriteLine("Ответ " + res);
Console.ReadKey();