using Tyuiu.RadchenkoAV.Sprint5.Task4.V28.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #5 | Выполнил: РадченкоАВ | РППБ-25-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #5                                                               *");
Console.WriteLine("* Тема: Обработка файлов                                                  *");
Console.WriteLine("* Задание #4                                                              *");
Console.WriteLine("* Вариант #28                                                             *");
Console.WriteLine("* Выполнила: РадченкоАВ | РППБ-25-1                                       *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* Создать папку в ручную С:DataSprint5 и скопировать в неё файл) в котором*");
Console.WriteLine("* есть вещественное значение. Прочитать значение из файла и подставить    *");
Console.WriteLine("* вместо Х в формуле y = 3x^3/sin(x)                                      *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                        *");
Console.WriteLine("***************************************************************************");
string path = @"C:\DataSprint5\InPutDataFileTask4V28.txt";
Console.WriteLine("Данные в: " + path);
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Результат                                                               *");
Console.WriteLine("***************************************************************************");
double res = ds.LoadFromDataFile(path);
Console.WriteLine(res);
Console.ReadKey();